# Generated by Django 5.2.14 on 2026-05-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='amount_rwf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='amount_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='amount_rwf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='amount_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='wallet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
