# Generated by Django 5.2.14 on 2026-05-16 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_interest_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
