# Generated by Django 5.2.14 on 2026-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_last_interest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='id_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
