# Generated by Django 5.2.14 on 2026-05-19 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_referral_code_profile_referred_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralbonus',
            name='deposit',
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='deposit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='locked_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
