# Generated by Django 5.2.14 on 2026-05-19 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_referralbonus_deposit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralbonus',
            name='active',
        ),
        migrations.RemoveField(
            model_name='referralbonus',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='referralbonus',
            name='locked_profit',
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.deposit'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_bonus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_bonus', to=settings.AUTH_USER_MODEL),
        ),
    ]
