# Generated by Django 5.2.14 on 2026-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
