# Generated by Django 5.2.14 on 2026-05-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_supportmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
    ]
